<?php


namespace WilokeUnitTest\Controllers;


use PHPUnit\Framework\TestCase;
use WilokeUnit\Controllers\PostController;

class TestPostController extends TestCase
{
	/**
	 * @var string[]
	 */
	private $aData;
	/**
	 * @var PostController
	 */
	private $oPost;

	public function setUp()
	{
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->aData = [
			'content' => 'My Content',
			'title'   => 'My Title'
		];

		$this->oPost = new PostController();
	}

	public function testValidation()
	{
		$aValidation = $this->oPost->validation($this->aData);
		$this->assertArrayHasKey(
			'msg',
			$aValidation
		);

		return $aValidation;
	}

	/**
	 * @depends testValidation
	 */
	public function testPost(array $aValidation)
	{
		$postId = $this->oPost->post();

		$this->assertEquals(1, $postId);
	}
}
